{
    "id": 1234,
    "image_href": "https://list.am/",
    "title": "new_title",
    "price_value": 490000,
    "currancy": "AMD",
    "description": "description",
    "date_posted": datetime.datetime(2024, 4, 25, 0, 45, 13, 570194),
    "date_updated": None,
    "location": "some_location",
    "agent_status": False,
    "user_link": "https://list.am/user",
    "appliances": None,
    "garage": None,
    "rooms_count": None,
    "toilet_count": 1,
    "utility_bills_included": None,
    "furniture": None,
    "children_allowed": None,
    "animals_allowed": None,
    "total_area": None,
    "land_area": None,
    "prepayment": None,
    "appartment_state": None,
    "type": None,
    "building_type": None,
    "facilities": None,
    "floors_count": 1,
}

# result of get_info_for_each_item
[
    {
        "image_href": "https://s.list.am/f/229/79736229.webp",
        "title": "Двухэтажный каменный дом, Նիկոլ Դումանի փողոց в Арабкирe, 780 кв.м., 2 ванные, капитальный ремонт",
        "price_value": "3000",
        "currancy": "USD",
        "type": "Дом",
        "building_type": "Каменное",
        "total_area": "780 кв.м.",
        "floors_count": "2",
        "rooms_count": "6",
        "toilet_count": "2",
        "furniture": "Есть",
        "garage": "Два места",
        "appartment_state": "Капитальный ремонт",
        "land_area": "500 кв.м.",
        "children_allowed": "Да",
        "animals_allowed": "По договоренности",
        "utility_bills_included": "Не включены",
        "prepayment": "1 месяц",
        "description": "Сдается двухэтажный частный дом по улице Никола Думана. Он отремонтирован, оснащен необходимым имуществом и оборудованием. Имеет просторный двор. Подходит для различных видов деятельности. Переведено с армянского",
        "id": "20918667",
        "date_posted": "2024-04-18T14:23:03+00:00",
        "date_updated": "2024-04-24T09:26:00",
        "location": "Նիկոլ Դումանի փողոց, Երևան",
        "agent_status": True,
        "user_link": "https://list.am/user/1783670",
    }
]
