{
    "id": 1234,
    "image_href": "https://list.am/",
    "title": "title",
    "price_value": 490000,
    "currancy": "AMD",
    "description": "description",
    "date_posted": datetime.datetime(2024, 4, 25, 0, 45, 13, 570194),
    "date_updated": None,
    "location": "some_location",
    "agent_status": False,
    "user_link": "https://list.am/user",
    "appliances": None,
    "garage": None,
    "rooms_count": None,
    "toilet_count": 1,
    "utility_bills_included": None,
    "furniture": None,
    "children_allowed": None,
    "animals_allowed": None,
    "total_area": None,
    "land_area": None,
    "prepayment": None,
    "appartment_state": None,
    "type": None,
    "building_type": None,
    "facilities": None,
    "floors_count": 1,
}
